name: Build image
on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Quality"]
    types:
      - completed

jobs:
  docker:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: golauth/golauth:latest
