name: Build image
on:
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish mainline
        uses: elgohr/Publish-Docker-Github-Action@v5
        if: github.ref == 'refs/heads/main'
        with:
          name: golauth/golauth
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: "latest"

      - name: Publish release
        uses: elgohr/Publish-Docker-Github-Action@v5
        if: github.event_name ==  'release'
        with:
          name: golauth/golauth
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tag_semver: true
