name: Quality
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: quality
    runs-on: ubuntu-24.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: test
        run: |
          go install github.com/ory/go-acc@latest
          go install github.com/golang/mock/mockgen@v1.6.0
          go mod download
          go generate -v ./...
          go-acc --covermode=set -o coverage.txt ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=golauth
            -Dsonar.projectKey=golauth_golauth
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*_test.go,**/*.sql,**/*_mock.go,**/ops/**,src/infra/api/routes.go
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.go.coverage.reportPaths=coverage.txt
