name: Quality
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: quality
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: test
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
          make test

      - name: sonar
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=golauth
            -Dsonar.projectKey=golauth_golauth
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*_test.go,**/*.sql,**/mock/*_mock.go
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.go.coverage.reportPaths=/github/workspace/coverage.out
